a = complex(input("Enter first complex number "))
b = complex(input("Enter second complex number "))
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:",a/b)